yumroad/blueprints/landing.py
from flask import Blueprint, render_template
from flask_login import current_user
from sqlalchemy.orm import joinedload

from yumroad.extensions import cache
from yumroad.models import Store

landing_bp = Blueprint('landing', __name__)

@landing_bp.route('/')
@cache.cached(timeout=300, unless=lambda: current_user.is_authenticated)
def index():
    stores = Store.query.limit(3).all()
    return render_template('landing/index.html', stores=stores)

yumroad/blueprints/products.py
from flask import Blueprint, render_template, redirect, request, url_for, abort, flash
from flask_login import login_required, current_user

from yumroad.extensions import checkout

from yumroad.models import Product, db
from yumroad.forms import ProductForm

product_bp = Blueprint('product', __name__)

@product_bp.route('/')
def index():
    products = Product.query.all()
    return render_template('products/index.html', products=products)

@product_bp.route('/new', methods=['GET', 'POST'])
@login_required
def create():
    form = ProductForm()
    if form.validate_on_submit():
        price = form.price.data or 0
        product = Product(name=form.name.data,
                        description=form.description.data,
                        price_cents=int(price*100),
                        picture_url=form.picture_url.data,
                        creator=current_user,
                        store=current_user.store)
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('product.details', product_id=product.id))
    return render_template('products/new.html', form=form)


@product_bp.route('/<product_id>')
def details(product_id):
    product = Product.query.get_or_404(product_id)
    stripe_publishable_key = checkout.publishable_key
    stripe_session = checkout.create_session(product) or {}
    session_id = stripe_session.get('id')

    return render_template('products/details.html',
                            product=product,
                            stripe_publishable_key=stripe_publishable_key,
                            checkout_session_id=session_id)

@product_bp.route('/<product_id>/post_checkout')
def post_checkout(product_id):
    product = Product.query.get_or_404(product_id)
    purchase_state = request.args.get('status')
    post_purchase_session_id = request.args.get('session_id')
    if purchase_state == 'success' and post_purchase_session_id:
        flash("Thanks for purchasing {}. You will receive an email shortly".format(product.name), 'success')
    elif purchase_state == 'cancel' and post_purchase_session_id:
        flash("There was an error while attempting to purchase this product. Try again", 'danger')
    return redirect(url_for('.details', product_id=product_id))

yumroad/blueprints/users.py
from flask import Blueprint, render_template, redirect, request, url_for, abort, session, flash
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash

from yumroad.extensions import login_manager
from yumroad.models import User, Store, db
from yumroad.forms import LoginForm, SignupForm
from yumroad.email import send_pretty_welcome_message

user_bp = Blueprint('user', __name__)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

@login_manager.unauthorized_handler
def unauthorized():
    session['after_login'] = request.url
    return redirect(url_for('user.login'))

@user_bp.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in", 'warning')
        return redirect(url_for("product.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).one()
        login_user(user)
        flash("Logged in successfully.", "success")
        return redirect(url_for("product.index"))

    return render_template("users/login.html", form=form)

@user_bp.route('/register', methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("You are already logged in", 'warning')
        return redirect(url_for("product.index"))

    form = SignupForm()
    if form.validate_on_submit():
        user = User.create(form.email.data, form.password.data)
        db.session.add(user)
        store = Store(name=form.store_name.data, user=user)
        db.session.add(store)
        db.session.commit()

        send_pretty_welcome_message(user)
        login_user(user)
        flash("Registered succesfully.", "success")
        return redirect(session.get('after_login') or url_for("product.index"))

    return render_template("users/register.html", form=form)

@user_bp.route('/logout', methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('product.index'))
    # You may want to only allow access through a POST request

yumroad/templates/_formhelpers.html
{% macro render_field(field) %}
    <div class="form-group {% if field.errors %} has-error{% endif -%} {%- if field.flags.required %} required{% endif -%}">
        <label for="{{ field.name }}">{{ field.label }}</label>
        {% if field.description %}
            <small classname="text-muted" for="{{ field.name }}">({{ field.description }})</small>
        {% endif %}
        {{ field(class_=' '.join(['form-control', 'is-invalid' if field.errors else '']), **kwargs)|safe }}
        <ul class="invalid-feedback errors">
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endmacro %}

yumroad/templates/_macros.html
{% macro render_flashes() %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="container mt-4">
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        </button>
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
{% endmacro %}

yumroad/templates/_navbar.html
<nav class="navbar navbar-light bg-light justify-content-between">
    <div class="navbar-item">
        <a href="{{ url_for('landing.index') }}" class="navbar-brand">Yumroad</a>
    </div>
    <div class="navbar-item form-inline">
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('product.create') }}" class="navbar-link">
                Add Product
            </a>
            <a class="ml-3 navbar-link">{{ current_user.email }}</a>
            <a class="nav-link" href="{{ url_for('user.logout') }}">Log out</a>
        {% else %}
            <a class="nav-link" href="{{ url_for('user.register') }}">Register</a>
            <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
        {% endif %}
    </div>
</nav>

yumroad/templates/base_layout.html
{% from "_macros.html" import render_flashes %}

<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}{% endblock %} Yumroad
        </title>

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% assets "common_css" %}
            <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
        {% endassets %}

        {% assets "common_js" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"> </script>
        {% endassets %}

        {% block custom_assets %}

        {% endblock %}

    </head>
    <body>
        {% include '_navbar.html' %}

        {{ render_flashes() }}

        <div class="container mt-3 mb-3">
            {% block content %}{% endblock %}
       </div>

    </body>
</html>